### ISSUE TITLE
About await

### ISSUE THREAD

**Issue by Alexsey** [valtech-nyc/proposal-fsharp-pipelines#6]
In the current proposal, `x |> await f` is considered to be a Syntax Error because of its ambiguity because it's not clear whether it's `await f(x)` or `(await f)(x)` and I agree that it is really unclear

This is why I think the solution to remove the ambiguity could be to desugar this in two `await`s - `await (await f)(x)`. Because `await` of a non-promise value is the value itself it would always provide the expected result

The case where specifically `(await f)(x)` is required the `x |> (await f)` would look like intuitive - parenthesizes are explicitly couples `await` only with `f`

And `await f(x)` only has a sense if `f` is a function and not a promise so transforming `f` to `await f` should not affect valid code

The only supper weird thing that it may block is a function that acts like a promise and may be resolved to some other function. In this case, the user of such code would not be able to use it fully in the pipeline. But `x |> await f` looks like much more popular use case

**Comment by mAAdhaTTah** [comment]
Given that it's ambiguous looking at it, I'm not really inclined to resolve it by choosing one, as developers looking at the code have to remember the rule to understand how it parses. Additionally, `await f`, whereby `f` is a promise that resolves to a function, isn't a particular common case. People don't really write Promises that resolve to functions, so it might seem that `await f(x)` would be more useful.

Additionally, the current implementation allows you to consider `await` like a unary function, passing in a Promise, awaiting for its value, and continuing along the pipeline. I think this is far easier to understand, and denying alternative implementations makes the one usage more obvious and expected. Otherwise, you'd either end up with 2 potential ways of `await`, or choosing between two ambiguous implementations.

**Comment by Alexsey** [comment]
That is right, resolution into a function is like 0.1% of all cases. And 99.9% are resolution into a value. That is why it would resolve like exactly the same as it may be expected

Additional special case is something that would be nice to avoid, but all that long discussions prove that it is impossible - we need it. Treating `await` as a unary function is also a special case because you can not treat it as a function in any other place but pipeline. Because anywhere else it is a unary operator

So the point is not to have 2 potential ways of `await` and not to choose between them but to have both

And the main reason for this proposal - utilize obvious syntax for the common use case. It's nice to be able to be to write everyday code a little bit more compact and readable. And it will be more readable when a few items of the pipe would be on the same line. In case of multiline readability would be just the same

**Comment by mAAdhaTTah** [comment]
> That is why it would resolve like exactly the same as it may be expected

The problem is the expectation, when you write `await f`, is that it's awaiting the value `f` on the RHS. With this change, this would no longer be the case in a pipeline, so `x |> await f` and `await f` look the same but do very different things, which is confusing. `|> await` has no such expectations.

**Comment by Alexsey** [comment]
The simplest way of thinking about pipeline I can imagine is
```
x |> f
 ↳→→→→→↴
     f(x)

```
"like take the left side and move it to the right parenthesized". Hard to describe it easier :)

If you will look at it from this perspective you will see no confusion

**Comment by mAAdhaTTah** [comment]
That shorthand still implies this: `x |> await f` -> `(await f)(x)`.

**Comment by Alexsey** [comment]
no. Literally
```
x |> await f
 ↳→→→→→→→→→→↴
     await f(x)
```
and
```
x |> (await f)
 ↳→→→→→→→→→→→→↴
     (await f)(x)
```

With the F# proposal in its current state, it works absolutely literal. If we take from readme example
```js
promise
  |> await
  |> (x => doubleSay(x, ', '))
  |> capitalize
  |> (x => x + '!')
  |> (x => new User.Message(x))
  |> (x => stream.write(x))
  |> await
  |> console.log;
```
it would be desugared into
```js
console.log(
  await (x => stream.write(x))
  ((x => User.Message(x))
  ((x => x + '!')
  (capitalize
  ((x => doubleSay(x, ', '))
  (await promise)))))
)
```

**Comment by mAAdhaTTah** [comment]
Sure, to _you_. But to _me_, that's not what it implies. And that's the whole point: You can't shorthand-rule your way out of the inherent confusion `x |> await f` brings to the table.

Instead, we ban `x |> await f` and force you to choose from two different options that make your intentions explicit. If you want `(await f)(x)`, then `x |> (await f)`; if you want `await f(x)`, then `x |> f |> await`. Both of those have only one possible interpretation. There's no confusion. The syntactic overhead here is well worth the clarity and I don't see a good reason to choose between one of two bad options for what `x |> await f` should mean when we can sidestep the whole debate.

**Comment by Alexsey** [comment]
Ok, lets get back to the initial topic with desugaring this in two `await`. How can the behavior of `await (await f)(x)` be confusing? It actually await everything, no matter what was the intention of the author

**Comment by Alexsey** [comment]
Wouldn't you mind if I create a separate issue for "literal" approach for of treating pipeline, where the left side is just moving to the right parenthesized?

I think there is something to discuss as it brings such pros as:
* no need for special treatment of `await` for the pipeline - it remains unary operator like in all other parts of ES
* removers ambiguity of `x |> await f` - so it should not be wasted
* looks absolutely compatible with other parts of the proposal - so it's definitely a proposal to a current proposal and not a new one
* has very simple to understand naive formulation - "take the left side and move it to the right parenthesized"

**Comment by mAAdhaTTah** [comment]
> How can the behavior of `await (await f)(x)` be confusing?

This isn't confusing; it becomes confusing when you look at it from the "sugared" version.

> Wouldn't you mind if I create a separate issue for "literal" approach for of treating pipeline, where the left side is just moving to the right parenthesized?

You can open whatever issues you like (within reason). I was able to get involved in this process because of the low barrier to entry.

However, I suspect that approach will lead you to a dead-end, because you're mistaking the syntax for what's actually happening. We're not literally moving parentheses around; the pipeline operator is about _application_. We _apply_ the LHS to the RHS. Parentheses are how that application is expressed, but it's not what it actually does. It's still tinkering with the metaphor about the thing rather than the thing itself.
